### ISSUE TITLE
package hl7.au.fhir.template no longer on build server - needs ig.ini

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/hl7.au.fhir.template#1]
Builds of HL7AU FHIR IGs that point to the HL7AU template `hl7.au.fhir.template` fail due to this package no longer being present in the build server (ie https://build.fhir.org/ig/hl7au/).

This build failure occurs when building au-fhir-base or au-fhir-core **and** when the `hl7.au.fhir.template#current` package is not present in the local FHIR package cache. In this circumstance, the IG Publisher looks online for the package, as it is not found in the local cache. _Note that this occurs with building locally on a PC and the HL7 GitHub auto-builder._

See [this zulip thread in May 2022](https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Templates.20no.20longer.20triggering.20build) where it was identified that template repos in GitHub no longer auto-build without an ig.ini file. Subsequently, empty ig.ini files were added into these template repos so that the auto-builder succeeds - see this commit on the HL7 International base template https://github.com/HL7/ig-template-base/commit/e27d0bd17c0f09d34a611b206020dcbd43ee2a7f.

### Reproduce:
* delete (or rename) the `hl7.au.fhir.template#current` package in your FHIR package cache
* run IG publisher on au-fhir-base or au-fhir-core FHIR IG
* error is outputted to terminal with ` The package 'hl7.au.fhir.template' has no entry on the current build server `

### The fix
* add an empty ig.ini file at the root level of this repo

_Note_: this template is dependent on the [base HL7AU template](https://github.com/hl7au/hl7.au.base.template) (ie `hl7.au.base.template#current`) which suffers from the same issue. Therefore, a fix and rebuild of the base template is required before the fix and rebuild occurs on this repo.

**Comment by robeastwood-agency** [comment]
see associated issue https://github.com/hl7au/hl7.au.base.template/issues/2

**Comment by brettesler-ext** [comment]
fixed in https://github.com/hl7au/hl7.au.fhir.template/commit/37fc2e320cbb2513d2864e80bd4ad18fb11de84c
